---
include:
  - board: nice_nano_v2
    shield: corne_left nice_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right nice_oled
  - board: nice_nano_v2
    shield: settings_reset 